# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 08:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_no', models.CharField(max_length=11, unique=True)),
                ('language', models.CharField(max_length=11)),
                ('currency', models.CharField(max_length=11)),
            ],
        ),
    ]
