# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 10:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='providers',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='providers',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 11, 10, 25, 22, 38869, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
